apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdas-snapshot
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: rdas
spec:
  accessModes:
    - ${SNAPSHOT_ACCESS_MODE}
  resources:
    requests:
      storage: ${SNAPSHOT_STORAGE_SIZE}
