apiVersion: v1
kind: Secret
metadata:
  name: rdas-secret
  namespace: rdas
  labels:
    app.kubernetes.io/name: rdas
type: Opaque
stringData:
  # We will add SOAP credentials here if the configured SOAP service requires them.
  # The current public CountryInfo endpoint does not require credentials.
  SOAP_USERNAME: ""
  SOAP_PASSWORD: ""
