apiVersion: v1
kind: Service
metadata:
  name: rdas
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: rdas
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rdas
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
